version: 1
labels:
  - label: "bug"
    title: "^[\x60\x27\x22]?(fix|fixes|fixed|bug|issue)(?:\\([^\\(\\)]+\\))?!?[\x60\x27\x22]?:"
  - label: "enhancement"
    title: "^[\x60\x27\x22]?(feat|features|feature|enhancement|perf)(?:\\([^\\(\\)]+\\))?!?[\x60\x27\x22]?:"
  - label: "chore"
    title: "^[\x60\x27\x22]?(chore|build|ci|cd|ops|dev-ops|refactor|style|test|misc)(?:\\([^\\(\\)]+\\))?!?[\x60\x27\x22]?:"
  - label: "documentation"
    title: "^[\x60\x27\x22]?(docs|documentation|doc)(?:\\([^\\(\\)]+\\))?!?[\x60\x27\x22]?:"
  - label: "revert"
    title: "^[\x60\x27\x22]?(revert)(?:\\([^\\(\\)]+\\))?!?[\x60\x27\x22]?:"
  - label: "needs-alert"
    title: "^[\x60\x27\x22]?(?:build|ci|docs|feat|fix|perf|refactor|revert|style|test|misc)(?:\\([^\\(\\)]+\\))?(!)[\x60\x27\x22]?:"