name-template: 'SplitScale v$RESOLVED_VERSION 🐬'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Enhancements:'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Fixes:'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance:'
    label: 'chore'
  - title:  '📖 Documentation:'
    label:
      - 'docs'
      - 'documentation'
exclude-labels:
  - 'skip-changelog'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  # ✨ What's Changed:

  $CHANGES