name: Labels

on:
  pull_request:
    branches: [main]
    types:
      [opened, reopened, synchronize, labeled, unlabeled]
  pull_request_target:
    types:
      [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  assign-labels:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: Assign labels in pull request
    if: github.event.pull_request.merged == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Execute assign labels
        id: action-assign-labels
        uses: mauroalderete/action-assign-labels@v1
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          conventional-commits: |
            conventional-commits:
              - type: 'fix'
                nouns: ['FIX', 'Fix', 'fix', 'fix!', 'FIXED', 'Fixed', 'fixed']
                labels: ['bug']
              - type: 'feature'
                nouns: ['FEATURE', 'Feature', 'feature', 'FEAT', 'Feat', 'feat', 'feat!']
                labels: ['enhancement']
              - type: 'breaking_change'
                nouns: ['BREAKING CHANGE', 'BREAKING', 'MAJOR']
                labels: ['BREAKING CHANGE']
              - type: 'documentation'
                nouns: ['doc','docs','docu','document','documentation']
                labels: ['documentation']
              - type: 'build'
                nouns: ['build','rebuild']
                labels: ['build']
              - type: 'config'
                nouns: ['config', 'conf', 'cofiguration', 'configure']
                labels: ['config']
              - type: 'chore'
                nouns: ['chore', 'ci', 'bump', 'maintenance']
                labels: ['chore']
          maintain-labels-not-matched: false
          apply-changes: true