name: Label Manager

on:
- issues
- pull_request

jobs:
  assign-labels:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: Assign labels
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Assign labels
        id: action-assign-labels
        uses: srvaroa/labeler@master
        with:
          config_path: .github/labeler.yml
          use_local_config: true
          fail_on_error: false
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"